import type { Suggestions } from "@/lib/types";

const DIFFICULTY_LABEL: Record<string, string> = {
  beginner: "Beginner",
  intermediate: "Intermediate",
  advanced: "Advanced",
};

export default function SuggestionsPanel({ suggestions }: { suggestions: Suggestions }) {
  return (
    <div className="space-y-8">
      <div>
        <p className="text-base leading-relaxed" style={{ color: "var(--text-secondary)" }}>
          {suggestions.headline}
        </p>
        <p className="text-xs mt-2" style={{ color: "var(--text-muted)" }}>
          {suggestions.engine === "gemini"
            ? "✦ Generated by Gemini (free tier)"
            : "Generated by the built-in rules engine — add a free GEMINI_API_KEY to .env.local for AI-written suggestions."}
        </p>
      </div>

      <div>
        <h3 className="text-lg font-semibold mb-3">
          Based on your GitHub, here are {suggestions.projects.length} projects you should build
        </h3>
        <div className="grid gap-4 md:grid-cols-2">
          {suggestions.projects.map((p, i) => (
            <article key={p.name} className="card card-hover p-4 flex flex-col gap-2">
              <div className="flex items-start justify-between gap-2">
                <h4 className="font-semibold">
                  <span style={{ color: "var(--text-muted)" }}>{i + 1}. </span>
                  {p.name}
                </h4>
                <span
                  className="text-[11px] font-medium px-2 py-0.5 rounded-full whitespace-nowrap"
                  style={{ background: "var(--grid-hairline)", color: "var(--text-secondary)" }}
                >
                  {DIFFICULTY_LABEL[p.difficulty] ?? p.difficulty}
                </span>
              </div>
              <p className="text-sm italic" style={{ color: "var(--text-secondary)" }}>
                {p.tagline}
              </p>
              <p className="text-sm" style={{ color: "var(--text-secondary)" }}>
                {p.description}
              </p>
              <p className="text-sm">
                <span className="font-medium">Why you: </span>
                <span style={{ color: "var(--text-secondary)" }}>{p.whyYou}</span>
              </p>
              <div className="flex flex-wrap gap-1.5 mt-auto pt-1">
                {p.suggestedStack.map((tech) => (
                  <span
                    key={tech}
                    className="text-[11px] px-2 py-0.5 rounded-full border"
                    style={{ borderColor: "var(--border)", color: "var(--text-secondary)" }}
                  >
                    {tech}
                  </span>
                ))}
              </div>
            </article>
          ))}
        </div>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        <div>
          <h3 className="text-base font-semibold mb-2">Ready-to-paste resume bullets</h3>
          <ul className="list-disc pl-5 space-y-1.5 text-sm" style={{ color: "var(--text-secondary)" }}>
            {suggestions.resumeBullets.map((b) => (
              <li key={b}>{b}</li>
            ))}
          </ul>
        </div>
        <div>
          <h3 className="text-base font-semibold mb-2">Resume &amp; profile tips</h3>
          <ul className="list-disc pl-5 space-y-1.5 text-sm" style={{ color: "var(--text-secondary)" }}>
            {suggestions.resumeTips.map((t) => (
              <li key={t}>{t}</li>
            ))}
          </ul>
        </div>
      </div>

      {suggestions.strengths.length > 0 ? (
        <div>
          <h3 className="text-base font-semibold mb-2">What&apos;s already working</h3>
          <ul className="list-disc pl-5 space-y-1.5 text-sm" style={{ color: "var(--text-secondary)" }}>
            {suggestions.strengths.map((s) => (
              <li key={s}>{s}</li>
            ))}
          </ul>
        </div>
      ) : null}
    </div>
  );
}
