import type { Analysis, Suggestions } from "./types";
import { getTier } from "./tiers";
import { buildRoadmap } from "./roadmap";

/** Render the full report as paste-anywhere Markdown (README, notes, resume docs). */
export function buildMarkdownReport(a: Analysis, s: Suggestions | null): string {
  const tier = getTier(a.overallScore);
  const roadmap = buildRoadmap(a);
  const lines: string[] = [
    `# RepoLens report — @${a.profile.login}`,
    "",
    `**Score: ${a.overallScore}/100 (${tier.label})**${a.bench?.percentile != null ? ` · better than ${a.bench.percentile}% of ${a.bench.sample} analyzed profiles` : ""}`,
    "",
    `Languages: ${a.languages.map((l) => `${l.name} ${l.percent}%`).join(" · ") || "n/a"}`,
    `Activity: ${a.commits.last90Days} commits in the last 90 days (${a.commits.totalSampled} sampled)`,
    "",
    "## Top repositories",
    "",
    "| Repo | Score | README | Stars |",
    "|---|---|---|---|",
    ...a.repos.map(
      (r) =>
        `| [${r.name}](${r.htmlUrl}) | ${r.qualityScore}/100 | ${r.readmeScore === null ? "missing" : `${r.readmeScore}/100`} | ${r.stars} |`,
    ),
    "",
    "## Roadmap",
    "",
    ...roadmap.map((item) => `- [ ] ${item.title} (+${item.gain} pts) — ${item.detail}`),
  ];

  if (s) {
    lines.push("", "## 5 projects to build next", "");
    s.projects.forEach((p, i) => {
      lines.push(`${i + 1}. **${p.name}** — ${p.tagline}`, `   ${p.whyYou}`, "");
    });
    lines.push("## Resume bullets", "", ...s.resumeBullets.map((b) => `- ${b}`));
  }

  lines.push("", `---`, `Generated by [RepoLens](https://repolens.rianfernando.com/u/${a.profile.login})`);
  return lines.join("\n");
}
